#!/bin/bash
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# Tests artifacts contained in ${TINK_BASE_DIR}/release.
#
# By default when run locally this script executes tests directly on the host.
# The CONTAINER_IMAGE variable can be set to execute tests in a custom container
# image for local testing. E.g.:
#
# CONTAINER_IMAGE="us-docker.pkg.dev/tink-test-infrastructure/tink-ci-images/linux-tink-py-base:latest" \
#  sh ./kokoro/gcp_ubuntu/release/sdist/test/run.sh
#
# The user may specify TINK_BASE_DIR as the folder where to look for tink-py
# and its dependencies. That is:
#   ${TINK_BASE_DIR}/tink_cc
#   ${TINK_BASE_DIR}/tink_py
#
# NOTE: tink_cc is fetched from GitHub if not found.
set -euo pipefail

IS_KOKORO="false"
if [[ -n "${KOKORO_ARTIFACTS_DIR:-}" ]]; then
  IS_KOKORO="true"
fi
readonly IS_KOKORO

RUN_COMMAND_ARGS=()
if [[ "${IS_KOKORO}" == "true" ]]; then
  TINK_BASE_DIR="$(echo "${KOKORO_ARTIFACTS_DIR}"/git*)"
  source "${TINK_BASE_DIR}/tink_py/kokoro/testutils/py_test_container_images.sh"
  CONTAINER_IMAGE="${TINK_PY_BASE_IMAGE}"
  # Kokoro places artifacts generated by a parent job here.
  cp -r "$(echo "${KOKORO_GFILE_DIR}"/git*/tink_py/release)" \
    "${TINK_BASE_DIR}/tink_py"
  RUN_COMMAND_ARGS+=( -k "${TINK_GCR_SERVICE_KEY}" )
else
  TINK_BASE_DIR="$(dirname "$(pwd)")"
fi
readonly TINK_BASE_DIR
readonly CONTAINER_IMAGE

cd "${TINK_BASE_DIR}/tink_py"

if [[ ! -d release ]]; then
  echo "InvalidArgumentError: No 'release' folder found in $(pwd)" >&2
  exit 1
fi

if [[ -n "${CONTAINER_IMAGE:-}" ]]; then
  RUN_COMMAND_ARGS+=( -c "${CONTAINER_IMAGE}" )
fi
readonly RUN_COMMAND_ARGS

./kokoro/testutils/copy_credentials.sh "testdata" "all"
./kokoro/testutils/run_command.sh "${RUN_COMMAND_ARGS[@]}" \
  ./tools/distribution/test_dist.sh "release"
