workspace(name = "examples_python")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "tink_py",
    path = "..",
)

load("@tink_py//:tink_py_deps.bzl", "tink_py_deps")

tink_py_deps()

load("@tink_py//:tink_py_deps_init.bzl", "tink_py_deps_init")

tink_py_deps_init("tink_py")

load("@tink_py_pip_deps//:requirements.bzl", tink_py_install_pypi_deps="install_deps")

tink_py_install_pypi_deps()

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip_deps",
    quiet = False,
    requirements_lock = "@examples_python//:requirements.txt",
)

load("@pip_deps//:requirements.bzl", tink_py_example_install_pypi_deps="install_deps")

tink_py_example_install_pypi_deps()
