workspace(name = "examples_python")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

local_repository(
    name = "tink_py",
    path = "..",
)

# Note: sha256 is intentionally omitted as this is not a static resource.
# Whenever updated, clients should fetch the latest revision provided at
# this URL.
maybe(
    http_file,
    name = "google_root_pem",
    executable = 0,
    urls = ["https://pki.goog/roots.pem"],
)

load("@tink_py//:tink_py_deps.bzl", "tink_py_deps")

tink_py_deps()

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@tink_py//:tink_py_deps_init.bzl", "tink_py_deps_init")

tink_py_deps_init("tink_py")

load("@tink_py_pip_deps//:requirements.bzl", tink_py_install_pypi_deps="install_deps")

tink_py_install_pypi_deps()

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip_deps",
    extra_pip_args = ["--no-deps"],
    quiet = False,
    requirements_lock = "@examples_python//:requirements.txt",
)

load("@pip_deps//:requirements.bzl", tink_py_example_install_pypi_deps="install_deps")

tink_py_example_install_pypi_deps()
