load("@rules_python//python:defs.bzl", "py_library", "py_test")
load("@tink_py_pip_deps//:requirements.bzl", "requirement")

package(default_visibility = ["//:__subpackages__"])

py_library(
    name = "gcpkms",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
    visibility = ["//visibility:public"],
    deps = [
        ":_gcp_kms_client",
        ":_gcp_kms_mac",
        ":_gcp_kms_public_key_sign",
        ":_gcp_kms_public_key_verify",
    ],
)

py_library(
    name = "_gcp_kms_client",
    srcs = ["_gcp_kms_client.py"],
    srcs_version = "PY3",
    deps = [
        ":_gcp_kms_util",
        "//tink:tink_python",
        "//tink/aead",
        requirement("google-auth"),
        requirement("google-api-core"),
        requirement("google-cloud-kms"),
    ],
)

py_library(
    name = "_gcp_kms_mac",
    srcs = ["_gcp_kms_mac.py"],
    srcs_version = "PY3",
    deps = [
        ":_gcp_kms_util",
        "//tink:tink_python",
        "//tink/mac",
        requirement("google-api-core"),
        requirement("google-cloud-kms"),
        requirement("google-crc32c"),
    ],
)

py_library(
    name = "_gcp_kms_public_key_sign",
    srcs = ["_gcp_kms_public_key_sign.py"],
    srcs_version = "PY3",
    deps = [
        ":_gcp_kms_util",
        "//tink:tink_python",
        "//tink/signature",
        requirement("google-api-core"),
        requirement("google-cloud-kms"),
        requirement("google-crc32c"),
    ],
)

py_library(
    name = "_gcp_kms_public_key_verify",
    srcs = ["_gcp_kms_public_key_verify.py"],
    srcs_version = "PY3",
    deps = [
        ":_gcp_kms_util",
        "//tink:tink_python",
        "//tink/internal:big_integer_util",
        "//tink/proto:common_py_pb2",
        "//tink/proto:ecdsa_py_pb2",
        "//tink/proto:ml_dsa_py_pb2",
        "//tink/proto:rsa_ssa_pkcs1_py_pb2",
        "//tink/proto:rsa_ssa_pss_py_pb2",
        "//tink/proto:slh_dsa_py_pb2",
        "//tink/proto:tink_py_pb2",
        "//tink/signature",
        requirement("google-cloud-kms"),
        requirement("pyasn1"),
        requirement("pyasn1-modules"),
    ],
)

py_library(
    name = "_gcp_kms_util",
    srcs = ["_gcp_kms_util.py"],
    srcs_version = "PY3",
    deps = [
        "//tink:tink_python",
        requirement("google-api-core"),
        requirement("google-cloud-kms"),
        requirement("google-crc32c"),
        requirement("pyasn1"),
        requirement("pyasn1-modules"),
    ],
)

py_test(
    name = "_gcp_kms_aead_test",
    srcs = ["_gcp_kms_aead_test.py"],
    srcs_version = "PY3",
    deps = [
        ":gcpkms",
        "//tink:tink_python",
        "//tink/testing:helper",
        "@protobuf//:protobuf_python",
        requirement("absl-py"),
        requirement("google-api-core"),
        requirement("google-cloud-kms"),
    ],
)

py_test(
    name = "_gcp_kms_mac_test",
    srcs = ["_gcp_kms_mac_test.py"],
    srcs_version = "PY3",
    deps = [
        ":_gcp_kms_mac",
        "//tink:tink_python",
        "@protobuf//:protobuf_python",
        requirement("absl-py"),
        requirement("google-api-core"),
        requirement("google-cloud-kms"),
        requirement("google-crc32c"),
    ],
)

py_test(
    name = "_gcp_kms_public_key_sign_test",
    srcs = ["_gcp_kms_public_key_sign_test.py"],
    srcs_version = "PY3",
    deps = [
        ":_gcp_kms_public_key_sign",
        ":_gcp_kms_util",
        "//tink:tink_python",
        "@protobuf//:protobuf_python",
        requirement("absl-py"),
        requirement("google-api-core"),
        requirement("google-cloud-kms"),
        requirement("google-crc32c"),
    ],
)

py_test(
    name = "_gcp_kms_public_key_verify_test",
    srcs = ["_gcp_kms_public_key_verify_test.py"],
    srcs_version = "PY3",
    deps = [
        ":_gcp_kms_public_key_verify",
        ":_gcp_kms_util",
        "//tink:tink_python",
        "@protobuf//:protobuf_python",
        requirement("absl-py"),
        requirement("google-api-core"),
        requirement("google-cloud-kms"),
        requirement("google-crc32c"),
    ],
)

py_test(
    name = "_gcp_kms_util_test",
    srcs = ["_gcp_kms_util_test.py"],
    srcs_version = "PY3",
    deps = [
        ":_gcp_kms_util",
        "//tink:tink_python",
        requirement("absl-py"),
        requirement("google-api-core"),
        requirement("google-cloud-kms"),
        requirement("google-crc32c"),
    ],
)

py_test(
    name = "_gcp_kms_client_test",
    srcs = ["_gcp_kms_client_test.py"],
    data = ["//testdata/gcp:credentials"],
    srcs_version = "PY3",
    deps = [
        ":gcpkms",
        "//tink/testing:helper",
        requirement("absl-py"),
        requirement("google-api-core"),
        requirement("google-cloud-kms"),
    ],
)

py_test(
    name = "_gcp_kms_client_integration_test",
    srcs = ["_gcp_kms_client_integration_test.py"],
    data = [
        "//testdata/gcp:credentials",
        "@google_root_pem//file",
    ],
    srcs_version = "PY3",
    tags = ["manual"],
    deps = [
        ":gcpkms",
        "//tink:tink_python",
        "//tink/aead",
        "//tink/testing:helper",
        requirement("absl-py"),
    ],
)

py_test(
    name = "_gcp_kms_integration_test",
    srcs = ["_gcp_kms_integration_test.py"],
    data = [
        "//testdata/gcp:credentials",
        "@google_root_pem//file",
    ],
    srcs_version = "PY3",
    tags = ["manual"],
    deps = [
        ":gcpkms",
        "//tink:secret_key_access",
        "//tink:tink_python",
        "//tink/aead",
        "//tink/aead:_kms_aead_key_manager",
        "//tink/testing:helper",
        requirement("absl-py"),
    ],
)
